from datetime import datetime
import json

class ResponseEngine:

    def generate_evidence_package(self, account_id: str, risk_result: dict, graph_report: dict):
        """Generate court-ready evidence package for ED/CBI"""

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        risk_score = risk_result.get('risk_score', 0)
        risk_level = risk_result.get('risk_level', 'CLEAR')
        mule_type = risk_result.get('mule_type', 'N/A')
        flags = risk_result.get('flags', [])
        shap_explanation = risk_result.get('shap_explanation', '')
        action = risk_result.get('recommended_action', '')

        # STR (Suspicious Transaction Report) for FIU-IND
        str_report = self.generate_str(account_id, risk_result, timestamp)

        # Regulatory alerts
        regulatory = self.generate_regulatory_alerts(account_id, risk_score, risk_level)

        # Chain of custody
        chain_of_custody = self.build_chain_of_custody(account_id, graph_report)

        evidence_package = {
            "evidence_id": f"TNX-{datetime.now().strftime('%Y%m%d%H%M%S')}-{account_id}",
            "generated_at": timestamp,
            "system": "TraceNetX v2.0 | Team OMEGA 404",
            "account_summary": {
                "account_id": account_id,
                "risk_score": risk_score,
                "risk_level": risk_level,
                "mule_classification": mule_type,
                "recommended_action": action,
            },
            "ml_analysis": {
                "shap_explanation": shap_explanation,
                "behavioral_flags": flags,
                "detection_method": "XGBoost + LightGBM + Random Forest ensemble + Isolation Forest anomaly detection"
            },
            "graph_intelligence": {
                "reverse_chain": graph_report.get('reverse_chain', {}),
                "community_membership": graph_report.get('community_detection', {}),
                "coordination_signals": graph_report.get('coordination_detection', {}),
                "identity_fusions": graph_report.get('identity_fusion', {}),
            },
            "chain_of_custody": chain_of_custody,
            "regulatory_output": regulatory,
            "str_report": str_report,
            "fir_summary": self.generate_fir_summary(account_id, risk_result, chain_of_custody),
        }

        return evidence_package

    def generate_str(self, account_id: str, risk_result: dict, timestamp: str):
        """Generate FIU-IND compatible Suspicious Transaction Report"""
        return {
            "str_type": "Mule Account Detection",
            "reporting_entity": "Bank of India — TraceNetX v2.0",
            "report_date": timestamp,
            "subject_account": account_id,
            "risk_score": risk_result.get('risk_score', 0),
            "risk_level": risk_result.get('risk_level', 'CLEAR'),
            "suspicious_indicators": risk_result.get('flags', []),
            "ml_confidence": f"{risk_result.get('risk_score', 0):.1f}%",
            "shap_basis": risk_result.get('shap_explanation', ''),
            "regulatory_body": "FIU-IND",
            "status": "AUTO-GENERATED — Requires human review before submission",
            "note": "Generated by TraceNetX v2.0 AI/ML pipeline. SHAP explainability provided for regulatory compliance."
        }

    def generate_regulatory_alerts(self, account_id: str, risk_score: float, risk_level: str):
        """Generate alerts for I4C, NCRP, RBI watchlist"""
        alerts = []

        if risk_score >= 70:
            alerts.append({
                "body": "I4C (Indian Cybercrime Coordination Centre)",
                "alert_type": "Mule Account — High Risk",
                "account": account_id,
                "action": "Cross-reference against active cybercrime complaints",
                "priority": "HIGH"
            })
            alerts.append({
                "body": "NCRP (National Cyber Crime Reporting Portal)",
                "alert_type": "Mule Account Match",
                "account": account_id,
                "action": "Match against victim complaint tickets",
                "priority": "HIGH"
            })

        if risk_score >= 85:
            alerts.append({
                "body": "ED/CBI Referral",
                "alert_type": "Criminal Network Node",
                "account": account_id,
                "action": "Immediate investigation referral",
                "priority": "CRITICAL"
            })
            alerts.append({
                "body": "RBI Crypto Watchlist",
                "alert_type": "Monitor crypto gateway transactions",
                "account": account_id,
                "action": "Flag any transfers to known exchange deposit addresses",
                "priority": "HIGH"
            })

        return {
            "total_alerts": len(alerts),
            "alerts": alerts,
            "fiu_ind_str_required": risk_score >= 50,
            "immediate_freeze_required": risk_score >= 85
        }

    def build_chain_of_custody(self, account_id: str, graph_report: dict):
        """Build legal chain of custody from graph intelligence"""
        chains = graph_report.get('reverse_chain', {}).get('reverse_chains', [])

        custody_entries = []
        for chain in chains:
            custody_entries.append({
                "entry_point": chain.get('entry_point', 'Unknown'),
                "exit_point": chain.get('exit_point', 'Unknown'),
                "hops": chain.get('hops', 0),
                "chain": " → ".join(chain.get('chain', [])),
                "amounts": chain.get('amounts', []),
                "legal_note": f"Fund flow documented across {chain.get('hops', 0)} accounts"
            })

        return {
            "subject_account": account_id,
            "total_chains": len(custody_entries),
            "fund_flow_chains": custody_entries,
            "legal_admissibility": "Evidence generated by certified AI system with SHAP explainability — suitable for FIR filing"
        }

    def generate_fir_summary(self, account_id: str, risk_result: dict, chain_of_custody: dict):
        """Generate FIR-ready summary for police filing"""
        flags = risk_result.get('flags', [])
        risk_level = risk_result.get('risk_level', 'CLEAR')
        mule_type = risk_result.get('mule_type', 'N/A')

        summary_lines = [
            f"SUBJECT ACCOUNT: {account_id}",
            f"CLASSIFICATION: {risk_level} — {mule_type}",
            f"RISK SCORE: {risk_result.get('risk_score', 0):.1f}/100",
            "",
            "SUSPICIOUS BEHAVIOR DETECTED:",
        ]
        for flag in flags:
            summary_lines.append(f"  • {flag}")

        summary_lines += [
            "",
            "AI ANALYSIS BASIS (SHAP):",
            f"  {risk_result.get('shap_explanation', 'N/A')}",
            "",
            f"FUND FLOW CHAINS IDENTIFIED: {chain_of_custody.get('total_chains', 0)}",
            "",
            "RECOMMENDED ACTION:",
            f"  {risk_result.get('recommended_action', 'N/A')}",
            "",
            "Generated by: TraceNetX v2.0 | Team OMEGA 404 | Sri Sairam Engineering College",
            "System: AI/ML Mule Account Intelligence Platform",
        ]

        return "\n".join(summary_lines)

    def get_graduated_response(self, risk_score: float):
        """Return graduated response recommendation"""
        if risk_score >= 85:
            return {
                "level": "CRITICAL",
                "score_range": "85-100",
                "color": "#FF0000",
                "action": "Immediate freeze + STR filing + ED/CBI referral",
                "timeline": "Within 1 hour",
                "notify": ["Bank Security", "ED/CBI", "FIU-IND", "I4C"]
            }
        elif risk_score >= 70:
            return {
                "level": "HIGH",
                "score_range": "70-84",
                "color": "#FF4500",
                "action": "Account freeze + investigation + police referral",
                "timeline": "Within 24 hours",
                "notify": ["Bank Security", "Local Police", "FIU-IND"]
            }
        elif risk_score >= 50:
            return {
                "level": "MEDIUM",
                "score_range": "50-69",
                "color": "#FFA500",
                "action": "Enhanced monitoring + bank outreach + customer interview",
                "timeline": "Within 72 hours",
                "notify": ["Bank Compliance", "Customer Service"]
            }
        elif risk_score >= 30:
            return {
                "level": "LOW",
                "score_range": "30-49",
                "color": "#FFD700",
                "action": "Watch list + periodic review",
                "timeline": "Weekly review",
                "notify": ["Bank Compliance"]
            }
        else:
            return {
                "level": "CLEAR",
                "score_range": "0-29",
                "color": "#00FF00",
                "action": "No action — continue standard monitoring",
                "timeline": "Standard cycle",
                "notify": []
            }

# Global instance
response_engine = ResponseEngine()
